
package logika.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * Wed Apr 26 22:05:44 CEST 2017
 * Generated source version: 3.1.4.redhat-1
 */

@XmlRootElement(name = "discountCartResponse", namespace = "http://logika/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "discountCartResponse", namespace = "http://logika/")

public class DiscountCartResponse {

    @XmlElement(name = "return")
    private logika.Cart _return;

    public logika.Cart getReturn() {
        return this._return;
    }

    public void setReturn(logika.Cart new_return)  {
        this._return = new_return;
    }

}

