
package logika.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * Sun Apr 23 21:39:06 CEST 2017
 * Generated source version: 3.1.4.redhat-1
 */

@XmlRootElement(name = "getMostExpensiveProductResponse", namespace = "http://logika/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMostExpensiveProductResponse", namespace = "http://logika/")

public class GetMostExpensiveProductResponse {

    @XmlElement(name = "return")
    private logika.Product _return;

    public logika.Product getReturn() {
        return this._return;
    }

    public void setReturn(logika.Product new_return)  {
        this._return = new_return;
    }

}

